### ISSUE TITLE
Imena atributov se začnejo z malo začetnico

### ISSUE THREAD

**Issue by andrejbauer** [damjanm/Vaje-iz-racunanja#3]
V definiciji razreda `Platno` vidimo atribute `ButtonPet`, `ButtonDeset`, ... Po dogovoru se piše z veliko začetnico imena razredov. Imena atributov so z malo. (Hint: uporabita "Rename" v "Refactor" in ne popravljaja na roko.)

**Comment by damjanm** [comment]
Rešeno z [https://github.com/damjanm/Vaje-iz-racunanja/commit/bfeb92d538d1e99a3813edf5bcd4ac2afa39ec77]()
