### ISSUE TITLE
Return

### ISSUE THREAD

**Issue by andrejbauer** [damjanm/Vaje-iz-racunanja#4]
Fino bi bilo, če bi lahko uporabnik oddal svoj odgovor s pritiskom na Return, da mu ni treba klikatim orda pride prav http://stackoverflow.com/questions/13731710/allowing-the-enter-key-to-press-the-submit-button-as-opposed-to-only-using-mo

**Comment by damjanm** [comment]
Razrešeno: https://github.com/damjanm/Vaje-iz-racunanja/commit/72e1b42bd45458b2d928799a86393948cff83f08](url)
