### ISSUE TITLE
Manjka `.project`

### ISSUE THREAD

**Issue by andrejbauer** [damjanm/Vaje-iz-racunanja#5]
Vajinega projekta ne morem importirat v Eclipse, ker repozitorij ne vsebuje datotek od projekta (`.project` in `.classpath` manjkata). A lahko prosim to popravita.

**Comment by damjanm** [comment]
Hmm datoteki `.project` in `.classpath` sta vsebovana v mapi Igra, ali nista ta prave? Zdaj sem spet downloadiral projekt, sem ga uvozil v Eclipse in je delovalo. Dodal sem par stvari, mogoče bo zdaj delalo?

**Comment by andrejbauer** [comment]
Ja, ne vem, zdaj tudi meni dela, sta pa po nepotrebnem dala zraven knjižnico miglayout, ki je sploh ne uporabljata.
